### ISSUE TITLE
Library uses fishy dependency fs

### ISSUE THREAD

**Issue by furstenheim** [open-wa/wa-decrypt-nodejs#125]
Hi,
I'm checking the source code of this project. I can see that one of the dependencies is "fs" which is listed in npm as a security problem https://www.npmjs.com/package/fs.

Why not using node fs?

**Comment by smashah** [comment]
This will be fixed ASAP.tbanks for bringing it up

**Comment by smashah** [comment]
@furstenheim this is now resolved in v4.0.0 thanks
