### ISSUE TITLE
Missing headers (possibly a small change by WA)

### ISSUE THREAD

**Issue by classic-gentleman** [open-wa/wa-decrypt-nodejs#15]
https://github.com/open-wa/wa-decrypt-nodejs/blob/d88b16cb75a5e530fe68b8d8762dbd2c83d2ee73/src/decrypt.ts#L23

I believe WA has changed something on their backend, it might be some proxy/caching artefact. Apparently it has become mandatory to include

```
'origin': 'https://web.whatsapp.com/',
'referer': 'https://web.whatsapp.com/'
```

as headers as well, otherwise the promise could be rejected with status 400 - Bad Request. Without this change the test won't pass as well (same kind of error). With the change the test saves the balls image. Afterwards it stops mattering if the headers are there or not - the request is accepted just fine.

**Comment by classic-gentleman** [comment]
(It might be sufficient to include just the `referer` header.)

**Comment by smashah** [comment]
Thanks @classic-gentleman . I ran the tests quite a bit and found no instances of 400, however it may be due to the fact my IP is probably whitelisted for the file as it was from one of my accounts running on the same machine. I'll add both now to be on the safe side.

**Comment by smashah** [comment]
@classic-gentleman change is live on v1.1.3

**Comment by classic-gentleman** [comment]
Whitelisting indeed explains it.
