### ISSUE TITLE
Problem with decrypt .xlsx files

### ISSUE THREAD

**Issue by jeferssonlemes** [open-wa/wa-decrypt-nodejs#166]
I've been using the library for over 1 year and in the meantime only 1 time we've had a problem with audio files having a few seconds cut off,
however this was fixed with a fix and so far we have never had any problems with any type of media, except excel files in .xlsx format, which when going through the decrypt function it becomes corrupted.

What I could analyze and I don't know if this is the reason for the problem is that, between the original file and the file that returns from the decrypt (this comparing the base64) there is a difference at the end of the file, everything is identical except the last 15 to 25 characters.

I will attach 2 links here:

* This is the original file uploaded directly:
[original_file](https://fileschat2.nyc3.digitaloceanspaces.com/public/system/60d1d181aa92eb60e9052aa6/chat/false_556584326793@c.us_41E62ED574116DAF5AD07254D52686DC/original_file.xlsx)

* This is the same however after going through the decrypt.
[after_decrypt](https://fileschat2.nyc3.digitaloceanspaces.com/public/system/60d1d181aa92eb60e9052aa6/chat/false_556584326793@c.us_41E62ED574116DAF5AD07254D52686DC/after_whatsapp_decrypt.xlsx)

I will also attach the 2 base64 files from the same files I used to analyze.
[example image](https://fileschat2.nyc3.digitaloceanspaces.com/public/system/60d1d181aa92eb60e9052aa6/chat/false_556584326793@c.us_41E62ED574116DAF5AD07254D52686DC/example.png)
[txt original Base64](https://fileschat2.nyc3.digitaloceanspaces.com/public/system/60d1d181aa92eb60e9052aa6/chat/false_556584326793@c.us_41E62ED574116DAF5AD07254D52686DC/originalbase64.txt)
[txt afterdecrypt base64](https://fileschat2.nyc3.digitaloceanspaces.com/public/system/60d1d181aa92eb60e9052aa6/chat/false_556584326793@c.us_41E62ED574116DAF5AD07254D52686DC/afterdecriptfilebase64.txt)

Once again I reinforce that I already use the same lib for all the rest of the files and none of them generates this type of error.

**Comment by smashah** [comment]
@jeferssonlemes I just tried to replicate the issue but am unable to. The file was decrypted successfully. Here's how I tested it.

1. Open this repo in my local computer.
2. Download the `original_file.xlsx`
3. Open `https://webhook.site`, copy the webhook address
4. Open WA WEB for host account A
5. Start EASY API (with `-w https://webhook.site/...` for host account B
6. Send `original_file.xlsx`from A to B
7. Copy the incoming message payload from webhook.site
8. Paste that message payload into `test/index.ts:8` (replace the `message` object)
9. `npm run test`

output:
```bash
Hash Validated: true
The file was saved!
```

If the hash is validated then the decrypted file is identical to the input file.

I then double checked the input file to your `txt original Base64` and it is identical.

Not sure what is going on with your setup but I will need more context and concrete reproduction steps.

Maybe you're using an older version of the decryption library?

**Comment by smashah** [comment]
@jeferssonlemes You are missing the `size` property from the test:

Doesnt work:
```javascript
{
    clientUrl: "https://mmg.whatsapp.net/d/f/AhImtrLSgRqUOdvvXEHr1b-amMsVMFeHx-b_useexVtI.enc",
    mediaKey: "7o9DE/4WxKox9RW9CKZlluhh26u2zo9iT0oP1q54d5g=",
    filehash: "dQMrMMuVa0Or5w+pkE5oSlOJ2ApaO/1e0GIaBX98KZU=",
    mimetype: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    type: "document"
  }
```

works:
```javascript
 {
    clientUrl: "https://mmg.whatsapp.net/d/f/AhImtrLSgRqUOdvvXEHr1b-amMsVMFeHx-b_useexVtI.enc",
    mediaKey: "7o9DE/4WxKox9RW9CKZlluhh26u2zo9iT0oP1q54d5g=",
    filehash: "dQMrMMuVa0Or5w+pkE5oSlOJ2ApaO/1e0GIaBX98KZU=",
    mimetype: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    type: "document",
    size: 15764
  }
```

**Comment by smashah** [comment]
@jeferssonlemes in v4.2.1 the decrypt message parameter now has a specific type `DecryptableMessage` instead of just `any` so you should see a ts error if the size is missing going forward.

As you can see from this line:
https://github.com/open-wa/wa-decrypt-nodejs/blob/56c55186ef08c10d05454b4e45485b666f9aace8/src/decrypt.ts#L89

The size property is required to fix padding issues.

Thanks

**Comment by jeferssonlemes** [comment]
We tested it here and it worked **perfectly**, we didn't pay attention to the parameter as in general we never need to use it.
Anyway thank you very much for the fantastic lib and for this help 🤜🤛.
