### ISSUE TITLE
webp extension is blank

### ISSUE THREAD

**Issue by tadeubarbosa** [open-wa/wa-decrypt-nodejs#39]
Hi!
I'm getting a blank image file when I receive a sticker. The extension is .webp, the another extensions are fine.

![image](https://user-images.githubusercontent.com/4499999/86486166-013c5600-bd31-11ea-9709-c97dedbd0f63.png)

**Comment by kauly** [comment]
Same here.

**Comment by smashah** [comment]
This method doesn't work with stickers yet. It currently decrypts the background for the sticker/webp which is usually blank

**Comment by smashah** [comment]
@kauly @tadeubarbosa v2.1.1 will be able to decrypt stickers. However, it requires an update to `wa-automate`

commit: 5e23d559db583640df54d752bfe8924e08a87789

Please follow: https://github.com/open-wa/wa-automate-nodejs/issues/580

**Comment by smashah** [comment]
Feature is now working:

https://github.com/open-wa/wa-automate-nodejs/issues/580#issuecomment-661631434
