### ISSUE TITLE
Audio OGG Encryption/Decryption Loss of trailing bytes

### ISSUE THREAD

**Issue by kmirea** [open-wa/wa-decrypt-nodejs#43]
**Describe the bug**
Audio OGG decryption is losing some bytes.  In every test, there is between 4 to 12 bytes trimmed off / lost.  Resulting OGG from wa-decrypt is always a multiple of 16. (This is likely issue of block-mode decrypt, skipping any trailing bytes below block size (16/32 ?) .I Believe this may be the cause of the issue of losing a second from OGG sending.

**Steps to Reproduce**
Uploaded files for testing below:
1. Test File (Original OGG: 11204 bytes): www.indizaonline.co.za/file.ogg
2. Encoded File (WhatsApp Encoded - from ClientUrl): www.indizaonline.co.za/file.enc
3. Decoded File (Output from WA-Decrypt - 11200 bytes - 4 bytes trimmed from end): www.indizaonline.co.za/wadecrypt.oga
4. all three files above zipped: www.indizaonline.co.za/ogg_test.zip
5. File/Key info:
mediaKey: 'WYzZPAw9wN+2MIEu9owTxCv8DfWN3pghj5ZPBCrn5Uk='
filehash: 'eDo3djnfwGUxmViq8PH8kzb/wYDryu7KA4byvdWFM/Y='
uploadhash: 'kxTTUN3TxCSQSThjNF1heKvnzfreSxFuRbQqZnTYyJA='
size: 11204,

**create() code**
This is the code you use to create the client. e.g
```javascript
...
```

**Expected behavior**
Full OGG decrypted, without loss of bytes

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  Current Release / Default settings
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Ubuntu 18

**Additional context**
using php for testing (requires openssl extension / use phpfiddle.org):

$salt = base64_decode('e+nLIMCM2QRQX/Z/kT9iYkc6vQoSIHT+ZMOffiG2PlM=');
$iv = base64_decode('jOVmsDgmWsQ/gSQK/YMWcg==');
$data = substr($encoded_data, 0, -10);
$decrypted = (openssl_decrypt($data, 'aes-256-cbc', $salt, 0, $iv));
$resultOk = hash('sha256',$decrypted) == '783a377639dfc065319958aaf0f1fc9336ffc180ebcaeeca0386f2bdd58533f6';
echo $resultOk ? "ok":"failed";

**Comment by smashah** [comment]
I was able to improve it slightly by not slicing PTT types:

https://github.com/open-wa/wa-decrypt-nodejs/blob/c53ad8f3054da1be1ea5e4eb01a060004924e0e7/src/decrypt.ts#L69


However, there is still a bit missing.

**Comment by kmirea** [comment]
> Thanks for the clear and concise breakdown @kmirea
> However, there is still a bit missing. Do you have any other suggestions?

Let me dig into it.  I am intimately familiar with SHA & block ciphers, though from the binary side. Let me find a workable alternative to node's default cryto lib

**Comment by kmirea** [comment]
> However, there is still a bit missing. Do you have any other suggestions?

Ok, i think this may work:   Don't trim the initial 10 bytes,  decrypt the full bytes, then trim the result to the length defined inside the Msg object (size).  This will trim off the padding bytes, which in my example is 12 bytes (0xC).   I need to look into whether the same applies for the encryption (Ie: adding the padding bytes manually)

**Comment by kmirea** [comment]
Sorry for not being use to whole GIT thing :P, but :-

Decrypt.ts (decryptMedia)
`const mediaDataBuffer = magix(buff, message.mediaKey, message.type, **message.size**);
  return mediaDataBuffer;`

(magix)
`const magix = (fileData: any, mediaKeyBase64: any, mediaType: any, outputSize: any) => {
....
decoded = decoded.slice(0, outputSize);
  const mediaDataBuffer = Buffer.from(decoded, 'utf-8');
  return mediaDataBuffer;
`

Asssuming decoded is a bytearray ?

**Comment by smashah** [comment]
That's the thing. When a voice note comes through it doesn't slice any. What you've written there basically chops off x amount of bytes. X being the message.size. which I'm sure will end up in even less data

**Comment by kmirea** [comment]
So far so good with the following. Hashes of input & output perfectly match  message.uploadhash & message.filehash respectively.

**(decryptMedia)**
....
  let **upload_hash** = crypto.createHash('sha256').update(res.data).digest('base64');

  const buff = Buffer.from(res.data, 'binary');
  const mediaDataBuffer = magix(buff, message.mediaKey, message.type, **message.size**);

  let **file_hash** = crypto.createHash('sha256').update(mediaDataBuffer).digest('base64');

  let is_valid = {
    in: upload_hash == message.uploadhash,
    out: file_hash == message.filehash
  };
  console.log(is_valid);
  return mediaDataBuffer;

**(magix)**
const magix = (fileData: any, mediaKeyBase64: any, mediaType: any,**expectedSize:number**) => {
....
var decoded: any = decipher.update(encodedBytes);
  const mediaDataBuffer = trimPadding(decoded, expectedSize);
  return mediaDataBuffer;
};cvvar decoded: any = decipher.update(encodedBytes);
  const mediaDataBuffer = trimPadding(decoded, expectedSize);
  return mediaDataBuffer;
};var decoded: any = decipher.update(encodedBytes);
  const mediaDataBuffer = **trimPadding(decoded, expectedSize);**
  return mediaDataBuffer;
};
+++
const **trimPadding** = (data:any, expectedSize:number)  => {
  let padding = expectedSize % 16;
  if(padding > 0)
  {
    padding = 16 - padding;
    if((expectedSize + padding) == data.length)
    {
       console.log("trimmed: "+padding+" bytes");
       data = data.slice(0, data.length - padding);
    }
  }
  return Buffer.from(data, 'utf-8');
};

...........................
Ur thoughts ? :P

**Comment by kmirea** [comment]
btw, just fyi, the padding is with the byte value of padding length, repeated, ie pad length of 12  = 0xC * 12

**Comment by smashah** [comment]
Great work @kmirea I've added the code and some fixes to the padding. I've tested it with a file I created while watching a movie and it works perfectly! PTT no longer gets cut off!!

https://github.com/open-wa/wa-decrypt-nodejs/commit/88a8056a96dd0b2e71623f1488ed37ea5fcc761b

(If you use the test/index.ts, you should be able to hear 'Son of a bitch!' - which is exactly what is in the PTT to the millisecond)

One thing though, the output hashes do not match. No big deal to be honest (at least for now) as they never matched anyways. Test it out and let me know if there's anything we can do to get the output hashes to match up, otherwise, these changes are ready to ship!

Thanks again

**Comment by kmirea** [comment]
Most welcome, and Thank YOU for this amazing project. its a god send, allowing our non profit to stay in touch with youth in rural areas in south africa, its doing gods work :P  I'm just glad i could contribute in some small way, and will continue to where i can

With regard to the hashes not matching, i am suspecting its something small like hashing a buffer array vs string, or maybe the slicing,. Let me update & do some tests. will report back.

Cheers

**Comment by kmirea** [comment]
Hi !  ok here is the fix:-

in **magix**, remove this line:-
```encodedBytes = encodedBytes.slice(0, -10);```

Padding is only added at the time of encryption automaticallly, so there is no need for adding it, doing so corrupts the file, it only exists in encrypted data, will always be stripped on decrypt, if there is padding at all.

**FixPadding** (padding is 16 minus modulus)
```
const fixPadding = (data:Buffer, expectedSize:number)  => {
  let padding = expectedSize % 16;
  if(padding > 0)
  {
    padding = 16 - padding;
    if((expectedSize + padding) == data.length) {
       //console.log(`trimmed: ${padding} bytes`);
       data = data.slice(0, data.length - padding);
    }
  }
  return Buffer.from(data, 'utf-8');
};
```
Please test it out :) so far so good my side.

Cheers & best regards

**Comment by kmirea** [comment]
calculating padding in one line, perhaps cleaner:-
``` let padding = (16 - (expectedSize % 16)) & 0xf;```

**Comment by smashah** [comment]
@kmirea Awesome that makes sense. v2.0.0 released and hash verifying moved to `test/index.ts` with [docs](https://github.com/open-wa/wa-decrypt-nodejs#verifying-decryption). Thanks for helping with this!
