### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by dportabella** [open-wa/wa-decrypt-nodejs#66]
```
id='true_41********0@c.us_3EB0201B6B3EA660A0B8';
decryptMedia = require('@open-wa/wa-decrypt').decryptMedia;
client.getMessageById(id).then(message => decryptMedia(message).then(console.log));

Promise { <pending> }
> (node:37462) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/private/tmp/kk/node_modules/@open-wa/wa-decrypt/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/private/tmp/kk/node_modules/@open-wa/wa-decrypt/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/private/tmp/kk/node_modules/@open-wa/wa-decrypt/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:506:15)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:37462) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 34)
```

However, it works if I use this other message id:
```id='true_4********0@c.us_3EB0BDAAE8FDF920D479';```

Both ids are correct, with `message.mimetype = "image/jpeg"`, and both images are available on the android phone.

What can be the problem?

**Comment by smashah** [comment]
@dportabella how old is the message that is resulting in 404?

**Comment by dportabella** [comment]
hi @smashah.
the message is very old, but the photo is still available in the phone.

**Comment by smashah** [comment]
@dportabella when a media message is really old you have to force the device to re-upload it to WA's servers. You can do this through the open-wa and it is an insider's feature: 

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#forcestalemediaupdate

**Comment by smashah** [comment]
Todo:

- [ ] Add documentation on handling decryption 404s

- [ ] Add link to `forceStaleMediaUpdate` on 404

**Comment by smashah** [comment]
@dportabella If you'd like to trial the insider's key please let me know [via support chat](http://otechie.com/smashah)

**Comment by dportabella** [comment]
> @dportabella when a media message is really old you have to force the device to re-upload it to WA's servers. You can do this through the open-wa and it is an insider's feature:
> 
> https://open-wa.github.io/wa-automate-nodejs/classes/client.html#forcestalemediaupdate

I started using the library for a pet project. I wish I had known before that some of the features of this library require a license. The main README.md is not clear about this. Although, yes, now that you say it, there is an external link to "Get License Key". :(

**Comment by smashah** [comment]
@dportabella please message me in the support chat or [via email](shah@idk.uno)

**Comment by dportabella** [comment]
thanks @smashah !
